Introduce a new directory for tasks related to structs
kech45/Introduction-to-programming pull request #2
Opened 2023-01-03 23:43 UTC by kech45

2023-01-03 23:46 UTC, HakanSunay requested changes
The `README.md` file seems to be empty, please fill it in with some info.

2023-01-03 23:54 UTC, kech45 commented
> The `README.md` file seems to be empty, please fill it in with some info.

fixed.

2023-01-03 23:55 UTC, HakanSunay requested changes

2023-01-03 23:55 UTC, HakanSunay commented on structs/README.md
> +This directory tracks the solutions of the problems, listed in https://github.com/vasilzahariev/IP-Practicum-Tasks/tree/main/Week%2012%20-%20Structsgi
nit: redundant comma

2023-01-03 23:59 UTC, HakanSunay commented
LGTM 🚢

2023-01-03 23:59 UTC, merged

2023-01-04 00:03 UTC, kech45 commented
closes #1